--------- HANDS ON 3 --------------------
---- TASK 1 -------
--35
select s.student_id, s.first_name,s.last_name, count(e.course_id) as course_count
from students s inner join enrollments e on s.student_id=e.student_id
group by s.student_id, s.first_name, s.last_name
having count(e.course_id) > ( select avg(totcourse_count) from 
					   (select count(course_id) as totcourse_count from enrollments
group by student_id) as totcourse_count  );


--36
select c.course_name, c.course_id from courses c inner join enrollments e on c.course_id=e.course_id group by c.course_name , c.course_id having count(case when e.grade='A' then 1 END)= count(e.enrollment_id);

--37
select p.professor_id, p.prof_name, d.dept_name from professors p inner join departments d on p.department_id=d.department_id where p.salary> (select avg(salary) from professors where department_id=d.department_id group by department_id) ;

--38
select d.dept_name, round(dept_stats.avg_salary,2) as avg_dept_salary
from departments d 
inner join (select department_id, avg(salary) as avg_salary from professors group by department_id) as dept_stats on d.department_id=dept_stats.department_id where dept_stats.avg_salary > 85000;

---------- TASK 2 -------------

--39
create or replace view vw_student_enrollment_summary as
select concat(s.first_name,' ',s.last_name) as stud_name, d.dept_name, 
coalesce(metric.cnt,0) as enrollment_count,
coalesce(metric.avggpa,0) as gpa from students s inner join departments d on s.department_id=d.department_id left join 
(select student_id, count(course_id) as cnt,round(avg(case grade 
							 when 'A'THEN 5
							 WHEN 'B' THEN 4
							 WHEN 'C' THEN 3
							 WHEN 'D' THEN 2
							 WHEN 'E' THEN 1
							 WHEN 'F' THEN 0
							 ELSE NULL
							 END ),2) as avggpa from enrollments group by student_id) AS metric on s.student_id=metric.student_id;

select * from vw_student_enrollment_summary;

--40
create or replace view vw_course_stats as
select c.course_name, c.course_code,
coalesce(metrics.cnt, 0) as enrollment_count,
coalesce(metrics.avggpa,0.00) as average_gpa
from courses c left join (select course_id,count(course_id) as cnt,
		  round(avg(case grade
				    when 'A'THEN 5
					WHEN 'B' THEN 4
					WHEN 'C' THEN 3
					WHEN 'D' THEN 2
					WHEN 'E' THEN 1
					WHEN 'F' THEN 0
					ELSE NULL
				   end),2) as avggpa from enrollments group by course_id) as metrics on c.course_id=metrics.course_id;
					
select * from vw_course_stats;

--41
select stud_name from vw_student_enrollment_summary where gpa>3.0;	

--42
--update vw_student_enrollment_summary set stud_name ='sam';
--ERROR:  Views that do not select from a single table or view are not automatically updatable.cannot update view "vw_student_enrollment_summary" 
--Multi-table views cannot be updated because views do not store data physically on the disk. Rather they are a virtual representation of data from two or more tables. In order to update the data in the views, data must be first updated in the original tables from which the view derives the base data. 

--43
drop view if exists vw_student_enrollment_summary;
create view vw_student_enrollment_summary as 
select student_id,
    course_id,
    grade,
    enrollment_date
FROM enrollments
WHERE grade IS NOT NULL 
WITH CHECK OPTION;

----------- task 3----------
-------- STORED PROCEDURES--------

--44
create or replace function fn_enroll_student(
	p_student_id INT,
	p_course_id int,
	p_enrollment_date date)
returns text as $$
declare 
	v_exists int;
begin
	--validation 1
	if not exists(select 1 from students where student_id=p_student_id)
		then 
			raise exception 'ERROR: STUDENT ID % DOES NOT EXISTS',p_student_id;
	end if;

	select count(*) into v_exists
	from enrollments where student_id=p_student_id and course_id=p_course_id;
	
	--validation 2
	if v_exists>0 then 
	raise exception 'Error: already enrolled';
	end if;
	
	insert into enrollments (student_id, course_id, enrollment_date)
	values (p_student_id, p_course_id, p_enrollment_date);
	return 'succesfully enrolled';
	

end;
$$ language plpgsql;

--45
create table department_transfer_log (
	log_id INT generated by default as identity primary key,
	student_id INT,
	old_department_id INT,
	new_department_id INT,
	transfer_time timestamp default current_timestamp);
	
create or replace function transfer_student_dept(
	p_student_id INT,
	p_new_department_id INT)
	returns text as $$
	declare 
		d_old_department_id INT;
	begin 
		select department_id into d_old_department_id from students where student_id=p_student_id;
		--CHECK IF OLD DEPT EXISTS
		if d_old_department_id is null then 
			Raise exception 'ERROR: student not found';
		end if;
		--UPDATE IN STUDENT TABLE

		update students set department_id=p_new_department_id where student_id=p_student_id;
		--INSERT LOG
		INSERT INTO department_transfer_log (student_id,old_department_id, new_department_id)
		values (p_student_id,d_old_department_id, p_new_department_id);
		
		RAISE NOTICE 'Transfer sequence finalized successfully.';
		
		return 'success:transfer verified';
		
		EXCEPTION 
    	WHEN OTHERS THEN
        	-- Catches any parsing/constraint failure, rolls back the session mutations entirely, and signals the host
        	RAISE NOTICE 'CRITICAL FAULT: Transfer failed. Rolling back changes.';
        	RAISE;
		End;
$$ language plpgsql;

--46
--TESTING robustness of function's transaction

select transfer_student_dept(1,-938);

select * from department_transfer_log;
--nothing was updated, perfectly fine table .

--47
begin;
SELECT fn_enroll_student(
    p_student_id := 3, 
    p_course_id := 1, 
    p_enrollment_date := '2026-06-22'::DATE
);
savepoint before_error;
select fn_enroll_student(4,-7,'2026-06-22');
rollback to savepoint before_error;
commit;
select * from enrollments;


