-------------------- HANDS ON 4 ----------------------
------ TASK1 : QUERY OPTIMIZATION ---------
--48
explain SELECT s.first_name, s.last_name, c.course_name FROM
enrollments e JOIN students s ON s.student_id = e.student_id JOIN courses c ON c.course_id =
e.course_id WHERE s.enrollment_year = 2022;

--RESULT 
--"Nested Loop  (cost=12.66..42.28 rows=7 width=354)"
--"  ->  Hash Join  (cost=12.51..40.90 rows=7 width=240)"
--"        Hash Cond: (e.student_id = s.student_id)"
--"        ->  Seq Scan on enrollments e  (cost=0.00..24.50 rows=1450 width=8)"
--"        ->  Hash  (cost=12.50..12.50 rows=1 width=240)"
--"              ->  Seq Scan on students s  (cost=0.00..12.50 rows=1 width=240)"
--"                    Filter: (enrollment_year = 2022)"
--"  ->  Index Scan using courses_pkey on courses c  (cost=0.15..0.20 rows=1 width=122)"
--"        Index Cond: (course_id = e.course_id)"

--49
--The plan executes a "Seq Scan" (Sequential Scan) on BOTH the 'enrollments' table (e) 
-- and the 'students' table (s). This indicates a full disk walk because no index bounds exist yet.


-- 50. Baseline Cost Metrics Log:
-- INFERENCE: 
--   - Overall Query Max Cost: 42.28 units.
--   - Enrollments Row Examination Estimate: 1450 rows scanned sequentially (Cost: 24.50).
--   - Students Filter Cost: 12.50 units to locate an estimated 1 row after filtering for year 2022.
-- [NOTE]: The 'courses' table successfully uses 'courses_pkey' (Index Scan) because primary keys 
-- automatically get an underlying default B-Tree index map generated by PostgreSQL.


--------- TASK 2 INDEXING ---------
--51
--creating a b-tree index on students.enrollment_year
create index idx_stud_enyr on students(enrollment_year);
EXPLAIN ANALYZE SELECT s.first_name, s.last_name, c.course_name FROM
enrollments e JOIN students s ON s.student_id = e.student_id JOIN courses c ON c.course_id =
e.course_id WHERE s.enrollment_year = 2022;

--52
create unique index idx_stud_enr_course on enrollments(student_id, course_id);

--53
create index idx_course_code on courses(course_code);

--54
explain analyze SELECT s.first_name, s.last_name, c.course_name FROM
enrollments e JOIN students s ON s.student_id = e.student_id JOIN courses c ON c.course_id =
e.course_id WHERE s.enrollment_year = 2022;

--1.Row Count Optimization: The total actual rows examined inside the execution scope dropped from 1,450 rows to a baseline of
--	13 rows because the previous plan was a simulation with generic statistics, whereas EXPLAIN ANALYZE reads the precise physical state of our local tables.

--2.Performance Timings: Execution time is at a very fast 0.221 ms.
--3.Index Selection Paradox: Even though indexes (idx_students_enrollment_year) are explicitly active, the planner continues to select a 'Seq Scan' 
--	across all tables. This is an INTENTIONAL engine optimization. Because the local datasets are extremely small (e.g., 13 rows in enrollments, 10 rows in students), reading the entire data page in one block costs less disk I/O than loading an index tree and hopping addresses. As the tables scale to 10,000+ rows in production, the planner will automatically swap from 'Seq Scan' to 'Index Scan' using our newly generated roadmap index models.

--55
create index idx_partial_enrollments_studid on enrollments(student_id) where grade is null;
