------pgAdmin
-----------TASK 1 
create table DEPARTMENTS(
	department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dept_name VARCHAR(100) NOT NULL,
	hod_name VARCHAR(100),
	budget DECIMAL(12,2));
	
create table STUDENTS(
	student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email varchar(50) UNIQUE NOT NULL,
	date_of_birth DATE,
	department_id INT,
	enrollment_year INT,
	
	Constraint fk_student_dept foreign key(department_id) references departments(department_id) on delete set null);

create table courses(
	course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	course_name varchar(50) not null,
	course_code varchar(20) unique,
	credits int,
	department_id int,
	constraint dept_course foreign key(department_id) references departments(department_id) on delete set null);
	
create table enrollments (
	enrollment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	student_id INT,
	course_id INT,
	enrollment_date DATE,
	grade CHAR(2) check ( grade in ('A','B','C','D','E','F')),
	constraint enrollment_stud foreign key(student_id) references students(student_id) on delete set null,
	constraint course_enrollments foreign key(course_id) references courses(course_id) on delete set null);

create table professors (
	professor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prof_name Varchar(100) not null,
	email varchar(100) unique,
	department_id int,
	salary decimal(10,2),
	constraint prof_dept foreign key(department_id) references departments(department_id) on delete set null);

alter table students drop constraint fk_student_dept;
alter table students add constraint dk_student_dept foreign key(department_id) references departments(department_id);

--task1 DDLs complete, now onto populating the database
-- departments
INSERT INTO departments (dept_name, hod_name, budget) VALUES
 ('Computer Science', 'Dr. Ramesh Kumar', 850000.00),
 ('Electronics', 'Dr. Priya Nair', 620000.00),
 ('Mechanical', 'Dr. Suresh Iyer', 540000.00),
 ('Civil', 'Dr. Ananya Sharma', 430000.00);
-- students
INSERT INTO students (first_name, last_name, email, date_of_birth, department_id,
enrollment_year) VALUES
 ('Arjun', 'Mehta', 'arjun.mehta@college.edu', '2003-04-12', 1, 2022),
 ('Priya', 'Suresh', 'priya.suresh@college.edu', '2003-07-25', 1, 2022),
 ('Rohan', 'Verma', 'rohan.verma@college.edu', '2002-11-08', 2, 2021),
 ('Sneha', 'Patel', 'sneha.patel@college.edu', '2004-01-30', 3, 2023),
 ('Vikram', 'Das', 'vikram.das@college.edu', '2003-09-14', 1, 2022),
 ('Kavya', 'Menon', 'kavya.menon@college.edu', '2002-05-17', 2, 2021),
 ('Aditya', 'Singh', 'aditya.singh@college.edu', '2004-03-22', 4, 2023),
 ('Deepika','Rao', 'deepika.rao@college.edu', '2003-08-09', 1, 2022);
-- courses
INSERT INTO courses (course_name, course_code, credits, department_id) VALUES
 ('Data Structures & Algorithms', 'CS101', 4, 1),
 ('Database Management Systems', 'CS102', 3, 1),
 ('Object Oriented Programming', 'CS103', 4, 1),
 ('Circuit Theory', 'EC101', 3, 2),
 ('Thermodynamics', 'ME101', 3, 3);
-- enrollments
INSERT INTO enrollments (student_id, course_id, enrollment_date, grade) VALUES
 (1, 1, '2022-07-01', 'A'), (1, 2, '2022-07-01', 'B'),
 (2, 1, '2022-07-01', 'B'), (2, 3, '2022-07-01', 'A'),
 (3, 4, '2021-07-01', 'A'), (4, 5, '2023-07-01', NULL),
 (5, 1, '2022-07-01', 'C'), (5, 2, '2022-07-01', 'A'),
 (6, 4, '2021-07-01', 'B'), (7, 5, '2023-07-01', NULL),
 (8, 1, '2022-07-01', 'A'), (8, 3, '2022-07-01', 'B');
-- professors
INSERT INTO professors (prof_name, email, department_id, salary) VALUES
 ('Dr. Anand Krishnan', 'anand.k@college.edu', 1, 95000.00),
 ('Dr. Meena Pillai', 'meena.p@college.edu', 1, 88000.00),
 ('Dr. Sunil Rajan', 'sunil.r@college.edu', 2, 82000.00),
 ('Dr. Latha Gopal', 'latha.g@college.edu', 3, 79000.00),
 ('Dr. Kartik Bose', 'kartik.b@college.edu', 4, 76000.00);


-------- TASK 2 --------- : ARCHITECTURAL NORMALIZATION AUDIT

-- 1. FIRST NORMAL FORM (1NF) COMPLIANCE:
-- Definition: All attributes must hold atomic values; repeating groups/arrays are barred.
-- Audit Analysis: Inside the 'STUDENTS' and 'DEPARTMENTS' tables, fields such as 'email', 
-- 'first_name', and 'dept_name' contain scalar, indivisible data types. If an un-normalized 
-- field like 'phone_numbers VARCHAR' existed holding comma-separated values ('9998887776, 9993332221'), 
-- it would violate 1NF, breaking index traversal. This schema satisfies 1NF.

-- 2. SECOND NORMAL FORM (2NF) COMPLIANCE:
-- Definition: Must satisfy 1NF, and all non-key columns must possess Full Functional 
-- Dependency on the complete Primary Key (No Partial Dependencies on composite keys).
-- Audit Analysis: The junction table 'ENROLLMENTS' uses an auto-incrementing identity key 
-- ('enrollment_id') as its PK. The alternate composite candidate key is (student_id, course_id). 
-- The non-key attributes 'enrollment_date' and 'grade' depend explicitly on the *combination* -- of who the student is AND which course they are taking. There are no attributes (like 
-- 'course_duration') that depend only on a subset ('course_id') of the candidate key. 
-- This schema satisfies 2NF.

-- 3. THIRD NORMAL FORM (3NF) COMPLIANCE:
-- Definition: Must satisfy 2NF, and no non-key attribute can possess a transitive 
-- dependency on the Primary Key through another non-key attribute (No Non-key -> Non-key dependencies).
-- Audit Analysis: Let's analyze the dependency chain:
--   student_id (PK) -> department_id (Foreign Key)
--   department_id   -> dept_name / hod_name
-- If 'dept_name' or 'hod_name' were stored directly inside the 'STUDENTS' table, a transitive 
-- dependency would form: student_id -> department_id -> dept_name. This would cause data 
-- mutation anomalies during department re-organizations. By isolating department details into 
-- the 'DEPARTMENTS' table and referencing only 'department_id', transitive dependencies are eliminated. 
-- This schema satisfies 3NF.



----------- TASK 3 --------- ( ALTER COMMANDS)
alter table students add column phone_number varchar(15);
alter table courses add column max_seats INT DEFAULT 60;
--GRADE CHECK IS ALREADY ENFORCED
ALTER TABLE departments rename column hod_name to head_of_dept;
alter table students drop column phone_number;


